drop table public.threads;
drop table audit.node_revisions;
drop table public.nodes;
drop table public.node_data_types;
drop table public.repository_members;
drop table public.repositories;
drop table public.namespaces;
drop table public.team_members;
drop table public.teams;
drop table public.users;
drop sequence public.global_id_seq;
drop function public.generate_id(text, integer);
drop function public.trigger_on_node_revision();
